version: '2.1'
services:
  tls:
    hostname: tls.magento2.docker
    image: 'magento/magento-cloud-docker-nginx:1.19-1.3.0'
    extends: generic
    networks:
      magento:
        aliases:
          - magento2.docker
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
      - UPSTREAM_HOST=web
      - UPSTREAM_PORT=8080
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      web:
        condition: service_started