# ./vendor/bin/ece-docker 'build:compose' --mode=developer --php='7.4' --nginx='1.19' --expose-db-port=3306 --no-varnish --with-cron
version: '2.1'
services:
  cron:
    hostname: cron.magento2.docker
    image: 'magento/magento-cloud-docker-php:7.4-cli-1.3.0'
    extends: generic
    command: run-cron
    environment:
      CRONTAB: '* * * * * root cd /app && /usr/local/bin/php bin/magento cron:run >> /app/var/log/cron.log'
    volumes:
      - '.:/app:delegated'
    networks:
      magento:
        aliases:
          - cron.magento2.docker
    depends_on:
      db:
        condition: service_healthy